Repository dd3tech/bui, pull requests merged in 2023-07, with the labels that each got.

#127 Feat(InputCurrency): add key press event on input currency
  src/components/Form/InputCurrency.tsx
Labels: enhancement

#128 fix: Adding decimalScale prop to Input type=currency
  src/components/Form/Input/CurrencyInput.tsx
Labels: bug

#130 Fix/input currency
  src/components/Form/Input/CurrencyInput.tsx
Labels: bug

#134 Fix(Sidebar): Change height skeleton sidebarlist
  src/components/SideBar/SkeletonSideBarList.tsx
Labels: bug

#135 fix: transition component exports
  exports.json
  package.json
Labels: refactor
