Repository dd3tech/bui, pull requests merged in 2023-03, with the labels that each got.

#14 feat: add missing exports of components
  exports.json
Labels: enhancement

#19 Fix(TabGroup): Add validation was added for the scroll of the tabs
  src/components/Tabs/TabGroup.tsx
Labels: bug

#22 fix: align button password when variant exist and refactor handle to …
  src/components/Form/Input/PasswordInput.tsx
Labels: bug

#29 fix(Tabgroup): fix scroll tabgroup
  src/components/Tabs/TabGroup.tsx
Labels: bug

#30 ref&fix: some components
  src/components/Buttons/ShapeButton.test.tsx
  src/components/Buttons/ShapeButton.tsx
  src/components/Circle/Circle.tsx
  src/components/FileViewer/FileViewer.tsx
Labels: bug, refactor
