Repository dd3tech/bui, pull requests merged in 2023-06, with the labels that each got.

#107 fix: add required input
  src/components/Form/FormLabel.tsx
  src/components/Form/Input/BaseInput.tsx
  src/components/Form/Input/CurrencyInput.tsx
  src/components/Form/Input/DateInput.tsx
  src/components/Form/Input/InputNumber.tsx
  src/components/Form/Input/PercentageInput.tsx
  src/components/Form/Select.tsx
  src/components/Form/TextArea.test.tsx
  src/components/Form/TextArea.tsx
Labels: bug

#109 Feat(Progress): add progress component
  exports.json
  package.json
  src/components/Progress/Progress.test.tsx
  src/components/Progress/Progress.tsx
  src/components/Progress/ProgressCircle.tsx
  src/components/Progress/ProgressLine.tsx
  src/components/Progress/index.ts
  src/components/Progress/progress.css
  src/components/index.ts
  src/stories/Progress.stories.tsx
Labels: enhancement

#115 fix: change validation value
  src/components/Form/Input/DateInput.tsx
Labels: bug

#118 feature: BarList component was added
  exports.json
  package.json
  src/components/BarList/BarLabel.tsx
  src/components/BarList/BarList.test.tsx
  src/components/BarList/BarList.tsx
  src/components/BarList/index.tsx
  src/components/index.ts
  src/stories/BarList.stories.tsx
Labels: enhancement

#121 fixed(BarList): added padding-right in values
  src/components/BarList/BarList.tsx
Labels: refactor

#126 fix(Sidebar): Add validation in SideBarItem
  src/components/SideBar/SideBarItem.tsx
Labels: bug
