Repository dd3tech/bui, pull requests merged in 2023-11, with the labels that each got.

#152 fix(Tab): add prop hidden
  src/components/Tabs/Tab.tsx
Labels: bug, refactor

#153 fix(useResize): Fix cases where window was undefined
  src/hooks/useResize.ts
Labels: bug

#154 feat(sidebar): added the possibility of rendering sub-sub items
  src/components/SideBar/SideBar.test.tsx
  src/components/SideBar/SideBar.tsx
  src/components/SideBar/SideBarItem.tsx
  src/stories/SideBar.stories.tsx
Labels: enhancement

#137 fix(exports): add, order and modification
  exports.json
  package.json
  src/common/Portal/Portal.tsx
  src/common/Portal/index.ts
  src/common/index.ts
  src/components/Card/index.ts
  src/components/FeedBackBox/index.ts
  src/components/FormControl/index.ts
  src/components/index.ts
Labels: refactor
